tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#93f7ba",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "outline-variant": "#c2c6d8",
        "on-background": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "inverse-primary": "#b1c5ff",
        "on-primary-fixed": "#001946",
        "on-tertiary-fixed-variant": "#004e5d",
        "primary-fixed": "#dae2ff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#77da9f",
        "tertiary-fixed": "#adecff",
        "primary": "#0057cd",
        "surface-bright": "#f8f9fa",
        "surface-container": "#edeeef",
        "secondary-container": "#90f4b7",
        "surface-tint": "#0057ce",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#5dd6f3",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-highest": "#e1e3e4",
        "on-primary-container": "#ffffff",
        "outline": "#727787",
        "secondary": "#006d41",
        "on-surface": "#191c1d",
        "on-secondary-fixed": "#002110",
        "on-secondary-container": "#007144",
        "surface-container-low": "#f3f4f5",
        "tertiary": "#00677a",
        "surface": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#008299",
        "background": "#f8f9fa",
        "primary-container": "#0d6efd",
        "on-secondary-fixed-variant": "#00522f",
        "on-primary-fixed-variant": "#00419e",
        "on-surface-variant": "#424655",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed": "#001f26",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b1c5ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
}
